### ISSUE TITLE
minor change in 2.2

### ISSUE THREAD

**Issue by vjcitn** [js2264/BiocBook#1]
https://github.com/js2264/BiocBook/blob/c00d60918acc2a2dd60dbc91fb78f291e925824e/pages/Chapter-2.qmd#L67

i think you want `if (!requireNamespace("BiocBook"))` ...

**Comment by js2264** [comment]
Yes indeed, thanks for your help! Fixed in https://github.com/js2264/BiocBook/commit/567408130c61b548f92f96a196f06944b8583432.
