### ISSUE TITLE
Docs: provide details on the PAT scopes

### ISSUE THREAD

**Issue by lgatto** [js2264/BiocBook#2]
I would find it useful to provide some details on the minimal set of scopes needed. Trial and error indicates that I need `repo` and `workflow`. `usethis::gh_token_help()`, that is mentioned in the quick *How to create a BiocBook* tells me that `user:email` is lacking. My book repo was created, and the (default) book has been build and is served as a github page, and I'm unsure if `user:email` is necessary and if I need to start again. It wouldn't be a major pain at this stage, but it would be easier to have known the above from the start.

**Comment by js2264** [comment]
Hi @lgatto, these specs (`repo`, `workflow` and `user:email`) are listed in the `BiocBookDemo` ([here](https://jserizay.com/BiocBookDemo/devel/pages/Chapter-2.html#creating-a-new-github-token)). Following your comment, I have added checks to internal login functions used in `init`, to ensure these 3 scopes are enabled. 

Note that you can modify the authorized scopes for any Github PAT here at any time: https://github.com/settings/tokens.
