### ISSUE TITLE
init() generates two .yml in .github/workflows

### ISSUE THREAD

**Issue by vjcitn** [js2264/BiocBook#4]
I see that there is an rworkflows.yml and biocbook.yml in the template.tar.gz ... and when
I push two jobs are run.  Are both needed?

**Comment by js2264** [comment]
Hi @vjcitn, thanks for this question. Only `biocbook` job is required to **render** the book, and this will be done on a Linux machine (just like what is done by the BBS for books). However, if you want to add extra checks to make sure that the code in your pages can be executed without errors from macOS / windows, the `rworkflows` builds/checks the package on 3 different machines (Linux / macOS / windows), and this also includes book rendering (although the book is not deployed to `gh-pages` with this action, only rendered as part of the build process). 
Feel free to remove `rworkflows.yml` file if you want to reduce the jobs to only those strictly needed for book deployment.
